editAreaLoader.lang["el"]={
new_document: "Νέο κενό αρχείο",
search_button: "Εύρεση και Αντικατάσταση",
search_command: "Αναζήτηση επόμενου / Αναζήτηση",
search: "Αναζήτηση",
replace: "Αντικατάσταση",
replace_command: "αντικατάσταση / Αναζήτηση",
find_next: "Εύρεση επόμενου",
replace_all: "αντικατάσταση όλων",
reg_exp: "Εκτεταμένη",
match_case: "Εύρεση του",
not_found: "δεν βρέθηκε.",
occurrence_replaced: "αντικαταστάθηκαν.",
search_field_empty: "Το πεδίο αναζήτησης είναι κενό",
restart_search_at_begin: "Η αναζήτηση ολοκληρώθηκε. Επανεκκίνηση απο την αρχή.",
move_popup: "μετακίνηση παραθύρου αναζήτησης",
font_size: "--Μέγεθος Γραματοσειράς--",
go_to_line: "πήγαινε στην γραμμή",
go_to_line_prompt: "πήγαινε στην γραμμή:",
undo: "Αναίρεση",
redo: "Ακύρωση αναίρεσης",
change_smooth_selection: "Ενεργοποίηση/απενεργοποίηση μερικών δυνατοτήτων (καλύτερη εμφάνιση αλλά περισσότερη κατανάλωση CPU)",
highlight: "Χρωματισμός κώδικα ενεργός/ανενεργός",
reset_highlight: "ανανέωση χρωματισμού κώδικα",
word_wrap: "Αναδίπλωση κειμένου",
help: "σχετικά",
save: "αποθήκευση",
load: "φόρτωση",
line_abbr: "Γρ",
char_abbr: "Χαρ",
position: "Θέση",
total: "Σύνολο",
close_popup: "Κλείσιμο",
shortcuts: "Συντομέυσεις",
add_tab: "προσθήκη tabulation",
remove_tab: "αφαίρεση tabulation",
about_notice: "Ειδοποίηση: Ο χρωματισμός κώδικα είναι για μικρό κείμενο",
toggle: "Επεξεργαστής κώδικα",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Φόρτωση...",
fullscreen: "Πλήρης προβολή",
syntax_selection: "--Συντακτικό--",
close_tab: "Κλείσιμο"
};
